### POST all filters
POST localhost:8081/habi/properties
Content-Type: application/json

{
  "filters": {
    "city": "medellin",
    "year": 2011,
    "status": "vendido"
  }
}

### POST one filter
POST localhost:8081/habi/properties
Content-Type: application/json

{
  "filters": {
    "city": "pereira",
    "status": "pre_venta",
    "year": 2020
  }
}

### POST without filters
POST localhost:8081/habi/properties
Content-Type: application/json

{
  "filters": {}
}