### POST all filters
POST localhost:8081/
Content-Type: application/json

{
  "filters": {
    "city": "medellin",
    "year": 2011,
    "status": "vendido"
  }
}

### POST one filter
POST localhost:8081/
Content-Type: application/json

{
  "filters": {
    "city": "bogota"
  }
}

### POST without filters
POST localhost:8081/
Content-Type: application/json

{
  "filters": {}
}