
### POST all filter
POST localhost:8081/habi
Content-Type: application/json

{
  "filters": {
    "city": "pereira",
    "status": "pre_venta",
    "year": 2020
  }
}

### POST year + city
POST localhost:8081/habi
Content-Type: application/json

{
  "filters": {
    "year": 2020,
    "city": "pereira"
  }
}

### POST year
POST localhost:8081/habi
Content-Type: application/json

{
  "filters": {
    "year": 2020
  }
}

### POST without filters
POST localhost:8081/habi/
Content-Type: application/json